apiVersion: v1
kind: Service
metadata:
  name: data-container-service
  labels:
    app: data-container
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: data-container