apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data
  namespace: myapps
spec:
  accesModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassname: nfs
