apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train
  name: train
  namespace: myapps
spec:
  replicas: 1 # hoeveel pods hebben we nodig?
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - image: gcr.io/light-quest-289208/train:0.0.1    # moet nog aangepast worden afhenkelijk van uiteindelijk image naam voorbeeld: gcr.io/de2020/trainingdbapi:0.0.1 # Docker image name, that we pushed to GCR
        name: train-api     # POD name
        volumeMounts:
        - mountPath: /usr/src/model
          name: model-repo
        ports:
        - containerPort: 5000
          protocol: TCP
        env:
        - name: MODEL_REPO
          value: /usr/src/myapps/model
        - name: DATA_API
          value: http://data-container-service:5000/data_container/test
      volumes:
      - name: model-repo
        persistentVolumeClaim:
          claimName: nfs-model-repo