apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: train
  name: train
  namespace: myapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - image: gcr.io/light-quest-289208/train:0.0.1
        name: train-api     # POD name
        volumeMounts:
        - mountPath: /usr/src/model
          name: model-repo
        ports:
        - containerPort: 5000
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: MODEL_REPO
          value: /usr/src/model
        - name: DATA_API
          value: http://data-container-service:5000/data_container/test
      volumes:
        - name: model-repo
          persistentVolumeClaim:
            claimName: nfs-model-repo