apiVersion: v1
kind: Service
metadata:
  name: predict-service
  labels:
    app: predict
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 5000
  selector:
    app: predict