apiVersion: v1
kind: Service
metadata:
  name: visualizer-service
  labels:
    app: visualizer
  namespace: myapps
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 5000
  selector:
    app: visualizer