apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visualizer
  name: visualizer
  namespace: myapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualizer
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      containers:
      - image: gcr.io/light-quest-289208/visualizer:0.0.1
        name: visualizer-api     # POD name
        ports:
        - containerPort: 5000
          protocol: TCP
        imagePullPolicy: Always
        env:
        - name: DATA_API
          value: http://data-container-service:5000/data_container/predict
